models.py
from app import db

from werkzeug.security import generate_password_hash, check_password_hash

listing = db.Table('listing',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('book_id', db.Integer, db.ForeignKey('book.id')))

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(50))
    isbn = db.Column(db.String(50))
    author = db.Column(db.String(50))
    condition = db.Column(db.String(50))
    edition = db.Column(db.String(50))

    listing = db.relationship('User', secondary=listing,
                           backref=db.backref('books', lazy='dynamic'))

    def __init__(self, title, isbn, author, condition, edition):
        self.title = title
        self.isbn = isbn
        self.author = author
        self.condition = condition
        self.edition = edition

    def __repr__(self):
        return '<Book %r>' % self.content


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50))
    pw_hash = db.Column('pw_hash', db.String(150))
    email = db.Column(db.String(50))
    is_active = True

    def __init__(self, username, password, email):
        self.username = username
        self.set_password(password)
        self.email = email

    def get_id(self):
        return unicode(self.id)

    def set_password(self, password):
        self.pw_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.pw_hash, password)

    def __repr__(self):
        return '<User %r>' % self.username

app.py
from flask import Flask, render_template, request, redirect, url_for, g
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
application = Flask(__name__)
application.secret_key = 'super secret key'
application.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///flaskr.db'
db = SQLAlchemy(application)


app = application

login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = 'main.login'

from models import User
@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

@app.before_request
def before_request():
    g.user = current_user

from routes import main
app.register_blueprint(main)
db.create_all()

routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, g

from flask_login import login_user, logout_user

main = Blueprint('main', __name__)

from app import db
from models import User, Book

@main.route('/addbook')
def addbook():
    return render_template("form.html")

@main.route('/books')
def index():
    books = Book.query.all()
    return render_template("index.html", books=books)


@main.route('/processbookform', methods=['GET','POST'])
def processbookform():
    title = request.form['title']
    isbn = request.form['isbn']
    author = request.form['author']
    condition = request.form['condition']
    edition = request.form['edition']
    book = Book(title, isbn, author, condition, edition)
    db.session.add(book)
    db.session.commit()
    return redirect(url_for('index'))

@main.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template('login.html')

    username = request.form['username']
    password = request.form['password']
    registered_user = User.query.filter_by(username=username).first()
    # if the username or password is invalid
    print(registered_user)
    print(registered_user.check_password(password))
    print(registered_user.id)
    if (registered_user is not None) and (registered_user.check_password(password)):

        login_user(registered_user)
        flash('Logged in successfully', 'success')
        print("sandwich")
        return redirect(url_for('main.index'))
    else:
        flash('Username or Password is invalid', 'error')
        print("salad")
    return redirect(url_for('main.login'))




@main.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))


@main.route('/', methods=['GET', 'POST'])
def register():
    if request.method == 'GET':
        return render_template('register.html')
    username = request.form['username']
    password = request.form['password']
    email = request.form['email']

    username_exists, email_exists = False, False
    try:
        username_exists = User.query.filter_by(username=username).first()
        email_exists = User.query.filter_by(email=email).first()
    except:
        pass

    if username_exists or email_exists:
        flash("Sorry, an account with this username or email already exists", "error")
    else:
        try:
            user = User(username,
                        password,
                        email)
            db.session.add(user)
            db.session.commit()
            flash('User successfully registered', "success")
            html = render_template('email/basic.html',
                                   username=username)
            print("bananas")
            #send_email("Welcome to the BisonShare!", email, html)
        except Exception as e:
            print("failed to create user: %s" % e)
            flash("Oops, something went wrong in creating your account", "error")

    return redirect(url_for('main.login'))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Bisonshare</title><!-- Latest compiled and minified CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet"><!-- Optional theme -->
	<link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet"><!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js">
	</script><!-- Latest compiled and minified JavaScript -->

	<script src="{{ url_for('static', filename='js/bootstrap.js') }}">
	</script>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button"><span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span></button> <a class="navbar-brand" href="#">Brand</a>
			</div><!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="active">
						<a href="#">Link <span class="sr-only">(current)</span></a>
					</li>
					<li>
						<a href="#">Link</a>
					</li>
					<li class="dropdown">
						<a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Dropdown <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li>
								<a href="#">Action</a>
							</li>
							<li>
								<a href="#">Another action</a>
							</li>
							<li>
								<a href="#">Something else here</a>
							</li>
							<li class="divider" role="separator"></li>
							<li>
								<a href="#">Separated link</a>
							</li>
							<li class="divider" role="separator"></li>
							<li>
								<a href="#">One more separated link</a>
							</li>
						</ul>
					</li>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input class="form-control" placeholder="Search" type="text">
					</div><button class="btn btn-default" type="submit">Submit</button>
				</form>
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="#">Link</a>
					</li>
					<li class="dropdown">
						<a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">Dropdown <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li>
								<a href="#">Action</a>
							</li>
							<li>
								<a href="#">Another action</a>
							</li>
							<li>
								<a href="#">Something else here</a>
							</li>
							<li class="divider" role="separator"></li>
							<li>
								<a href="#">Separated link</a>
							</li>
						</ul>
					</li>
				</ul>
			</div><!-- /.navbar-collapse -->
		</div><!-- /.container-fluid -->
	</nav>
    <div class="container">
        {% block body %} {% endblock %}
    </div>

</body>
</html>

templates/form.html
{% extends "base.html" %}
{% block body %}
    <form action="{{ url_for('processbookform') }}" method="POST" >
        Title: <input id='title' type="text" name="title" /><br />
        ISBN: <input type="text" name="isbn" /><br />
        Author: <input type="text" name="author" /><br />
        Condition: <input type="text" name="condition" /><br />
        Edition: <input type="number" name="edition" /><br />
        <input type="submit" value="Submit" >
    </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block body %}
    <h4>These are the coolest books</h4>

    {% for book in books%}
        <div class="col-md-4">
            <div class="well">
                <strong>Title:</strong> {{ book.title}} <br/>
                <strong>ISBN:</strong> {{ book.isbn}} <br/>
                <strong>Author:</strong> {{ book.author}} <br/>
                <strong>Condition:</strong> {{ book.condition}}<br/>
                <strong>Edition:</strong> {{ book.edition}}
            </div>
        </div>
    {% endfor %}

     <a href="/" >New Book</a>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block body %}
     <form action="{{ url_for('main.login') }}" method="POST" >
        Username: <input type="text" name="username" /><br />
        Password: <input type="text" name="password" /><br />
        <input type="submit" value="Submit" >
    </form>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block body %}
     <form action="{{ url_for('main.register') }}" method="POST" >
        Username: <input type="text" name="username" /><br />
        Email: <input type="text" name="email" /><br />
        Password: <input type="text" name="password" /><br />
        <input type="submit" value="Submit" >
    </form>
{% endblock %}

templates/registration.html
{% extends "base.html" %}
{% block body %}
     <form action="{{ url_for('app.processregistration') }}" method="POST" >
        Username: <input type="text" name="name" /><br />
        Email: <input type="text" name="email" /><br />
        Password: <input type="text" name="password" /><br />
        <input type="submit" value="Submit" >
    </form>
{% endblock %}